version: "3.8"
services:
  node-backend:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    volumes:
      - .:/app
