FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
EXPOSE 5000
COPY ML/modelforHotels/hotel_price_model.pkl /app/ML/modelforHotels/
COPY data/enhanced_hotels_dataset.csv /app/data/

CMD ["python", "Python/main.py"]
