# render.yaml
services:
  - type: web
    name: node-backend
    env: docker
    plan: free
    repo: https://github.com/Akarsh-2004/Pre-threat-Intellegence-
    dockerfilePath: ./Dockerfile.node
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - type: web
    name: python-backend
    env: docker
    plan: free
    repo: https://github.com/Akarsh-2004/Pre-threat-Intellegence-
    dockerfilePath: ./Dockerfile.python
    buildCommand: ""
    startCommand: "uvicorn Python_api_for_hotel_route:app --host 0.0.0.0 --port 5000"
    envVars:
      - key: PYTHON_ENV
        value: production
